// Component Categories Configuration
// Central registry for all CurioUI components

export interface ComponentMeta {
    slug: string;
    name: string;
    description: string;
    category: keyof typeof componentCategories;
    isPremium: boolean;
    isNew?: boolean;
    dependencies?: string[];
}

export const componentCategories = {
    backgrounds: {
        name: "Backgrounds",
        description: "Animated backgrounds and visual effects",
        icon: "Layers",
    },
    buttons: {
        name: "Buttons",
        description: "Interactive button and surface components",
        icon: "MousePointer",
    },
    cards: {
        name: "Cards",
        description: "Card layouts with hover effects",
        icon: "LayoutGrid",
    },
    text: {
        name: "Text",
        description: "Typography animations and effects",
        icon: "Type",
    },
    loaders: {
        name: "Loaders",
        description: "Loading states and spinners",
        icon: "Loader2",
    },
    effects: {
        name: "Effects",
        description: "Cursor effects and interactive elements",
        icon: "Sparkles",
    },
} as const;

// Component Registry
export const components: ComponentMeta[] = [
    // Backgrounds
    {
        slug: "ascii-media",
        name: "ASCII Media",
        description: "Convert video and images to real-time ASCII art with WebGL",
        category: "backgrounds",
        isPremium: false,
        isNew: false,
    },
    {
        slug: "components/backgrounds/click-spark",
        name: "Click Spark",
        description: "Spark burst animation on click interactions",
        category: "backgrounds",
        isPremium: false,
        isNew: true,
    },
    // Buttons / Surfaces
    {
        slug: "buttons/3d-button",
        name: "3D Button",
        description: "Button with 3D depth effect and ripple on hover",
        category: "buttons",
        isPremium: false,
        isNew: false,
    },
    {
        slug: "buttons/shine-button",
        name: "Shine Button",
        description: "Button with diagonal light sweep effect on hover",
        category: "buttons",
        isPremium: false,
        isNew: false,
    },
    {
        slug: "buttons/gradient-fill-button",
        name: "Gradient Fill Button",
        description: "Button that fills with gradient from bottom on hover",
        category: "buttons",
        isPremium: false,
        isNew: false,
    },
    {
        slug: "components/buttons/wet-button",
        name: "Wet Paint Button",
        description: "Dripping paint effect on hover",
        category: "buttons",
        isPremium: false,
        isNew: false,
        dependencies: ["framer-motion"],
    },
    {
        slug: "components/buttons/dot-expand-button",
        name: "Dot Expand",
        description: "Button with expanding dot animation on hover",
        category: "buttons",
        isPremium: false,
        isNew: true,
    },
    // Cards
    {
        slug: "components/spotlight-card",
        name: "Spotlight Card",
        description: "Card with gradient spotlight effect on hover",
        category: "cards",
        isPremium: false,
        isNew: false,
    },
    {
        slug: "tilted-card",
        name: "Tilted Card",
        description: "Card with 3D tilt effect that follows mouse",
        category: "cards",
        isPremium: false,
        isNew: true,
        dependencies: ["framer-motion"],
    },
    // Text Animations
    {
        slug: "components/text/a-s-c-i-i-text",
        name: "ASCIIText",
        description: "ASCIIText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/aurora",
        name: "Aurora",
        description: "Aurora animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/blur-text",
        name: "Blur Text",
        description: "Text that blurs in with staggered animation",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/click-spark",
        name: "ClickSpark",
        description: "Spark burst animation on click interactions",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/counter",
        name: "Counter",
        description: "Counter animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/decrypted-text",
        name: "DecryptedText",
        description: "DecryptedText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/folder",
        name: "Folder",
        description: "Folder animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/fuzzy-text",
        name: "Fuzzy Text",
        description: "Text that blurs and reveals on hover",
        category: "text",
        isPremium: false,
        isNew: false,
        dependencies: ["framer-motion"],
    },
    {
        slug: "components/text/gradient-text",
        name: "Gradient Text",
        description: "Animated gradient text with customizable colors",
        category: "text",
        isPremium: false,
        isNew: false,
        dependencies: ["framer-motion"],
    },
    {
        slug: "components/text/scroll-velocity",
    },
    {
        slug: "components/text/shiny-text",
        name: "Shiny Text",
        description: "Text with animated shine effect",
        category: "text",
        isPremium: false,
        isNew: true,
        dependencies: ["framer-motion"],
    },
    {
        slug: "components/text/text-pressure",
        name: "Text Pressure",
        description: "Text that responds to mouse movement with variable font weights",
        category: "text",
        isPremium: false,
        isNew: true,
    },
    {
        slug: "components/text/true-focus",
    },
    // Loaders
    {
        slug: "loaders/spiral-loader",
        name: "Spiral Loader",
        description: "Animated spiral loader with pulsing dots",
        category: "loaders",
        isPremium: false,
        isNew: true,
        dependencies: ["framer-motion"],
    },
    // Effects
    {
        slug: "components/effects/text-cursor",
        name: "Text Cursor",
        description: "Emoji/text trail that follows mouse cursor with smooth animations",
        category: "effects",
        isPremium: false,
        isNew: true,
        dependencies: ["framer-motion"],
    },
    {
        slug: "components/effects/electric-border",
        name: "Electric Border",
        description: "Turbulent, animated electric border effect using SVG filters",
        category: "effects",
        isPremium: false,
        isNew: true,
    },
,
    {
        slug: "text-animations/circular-text",
        name: "CircularText",
        description: "CircularText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/curved-loop",
        name: "CurvedLoop",
        description: "CurvedLoop animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/dock",
        name: "Dock",
        description: "Dock animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/electric-border",
        name: "ElectricBorder",
        description: "ElectricBorder animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/galaxy",
        name: "Galaxy",
        description: "Galaxy animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/ghost-cursor",
        name: "GhostCursor",
        description: "GhostCursor animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/glare-hover",
        name: "GlareHover",
        description: "GlareHover animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/glass-icons",
        name: "GlassIcons",
        description: "GlassIcons animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/glitch-text",
        name: "GlitchText",
        description: "GlitchText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/gooey-nav",
        name: "GooeyNav",
        description: "GooeyNav animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/gradient-blinds",
        name: "GradientBlinds",
        description: "GradientBlinds animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/gradient-text",
        name: "GradientText",
        description: "GradientText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/gradual-blur",
        name: "GradualBlur",
        description: "GradualBlur animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/grid-pulse",
        name: "GridPulse",
        description: "GridPulse animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/iridescence",
        name: "Iridescence",
        description: "Iridescence animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/letter-glitch",
        name: "LetterGlitch",
        description: "LetterGlitch animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/lightning",
        name: "Lightning",
        description: "Lightning animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/liquid-chrome",
        name: "LiquidChrome",
        description: "LiquidChrome animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/logo-loop",
        name: "LogoLoop",
        description: "LogoLoop animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/magnet",
        name: "Magnet",
        description: "Magnet animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/meta-balls",
        name: "MetaBalls",
        description: "MetaBalls animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/noise",
        name: "Noise",
        description: "Noise animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/orb",
        name: "Orb",
        description: "Orb animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/particles",
        name: "Particles",
        description: "Particles animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/plasma",
        name: "Plasma",
        description: "Plasma animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/prism",
        name: "Prism",
        description: "Prism animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/profile-card",
        name: "ProfileCard",
        description: "ProfileCard animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/ribbons",
        name: "Ribbons",
        description: "Ribbons animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/ripple-grid",
        name: "RippleGrid",
        description: "RippleGrid animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/rotating-text",
        name: "RotatingText",
        description: "RotatingText animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/scroll-stack",
        name: "ScrollStack",
        description: "ScrollStack animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/scroll-velocity",
        name: "ScrollVelocity",
        description: "ScrollVelocity animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/shape-blur",
        name: "ShapeBlur",
        description: "ShapeBlur animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },,
    {
        slug: "text-animations/spotlight-card",
        name: "SpotlightCard",
        description: "SpotlightCard animation effect",
        category: "text",
        isPremium: false,
        isNew: true,
    },];

// Helper functions
export function getComponentsByCategory(category: keyof typeof componentCategories) {
    return components.filter((c) => c.category === category);
}

export function getFreeComponents() {
    return components.filter((c) => !c.isPremium);
}

export function getPremiumComponents() {
    return components.filter((c) => c.isPremium);
}

export function getComponentBySlug(slug: string) {
    return components.find((c) => c.slug === slug);
}
